# Generated by Django 3.0.5 on 2020-04-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='prenom',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='surnom',
            field=models.TextField(default=''),
        ),
    ]
