# Generated by Django 3.0.5 on 2020-04-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20200419_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone_number',
            field=models.TextField(default=''),
        ),
    ]
