# Generated by Django 3.0.5 on 2020-04-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20200419_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
