# Generated by Django 3.0.5 on 2020-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20200420_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='artist',
            name='prenom',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='surnom',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
