# Generated by Django 3.0.5 on 2020-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20200420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
